##### Indexing & Slicing

In [2]:
import numpy as np

In [35]:
A = np.matrix([np.linspace(1, 5, 5), np.linspace(6, 10, 5), np.linspace(11, 15, 5)])

In [10]:
A[1]

matrix([[ 6.,  7.,  8.,  9., 10.]])

In [13]:
A[-3]

matrix([[1., 2., 3., 4., 5.]])

In [14]:
A[0:2]

matrix([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

In [15]:
A[:]

matrix([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.]])

In [16]:
A[0:-1]

matrix([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

In [17]:
A[:-1]

matrix([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

In [18]:
A[1:]

matrix([[ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.]])

In [19]:
A[0:4:2]

matrix([[ 1.,  2.,  3.,  4.,  5.],
        [11., 12., 13., 14., 15.]])

In [20]:
A[::-1]

matrix([[11., 12., 13., 14., 15.],
        [ 6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.]])

##### Views

In [31]:
B = A[:, :]

In [32]:
B

matrix([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.]])

In [33]:
B[:, :] = 0

In [34]:
A

matrix([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

###### Copy()

In [37]:
B = A.copy()

In [40]:
B[:, :] = 1

In [42]:
B

matrix([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

###### Fancy Indexing

In [47]:
indexes = np.arange(0, 3, 1)

In [49]:
A[indexes, indexes]

matrix([[ 1.,  7., 13.]])

###### Boolean Indexing

In [50]:
A > 5

matrix([[False, False, False, False, False],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]])

In [53]:
A[A > 5]

matrix([[ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.]])

##### Reshaping & Resizing

In [54]:
A.reshape(5,3)

matrix([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.]])

###### Flatten creates a new copy of the array

In [55]:
A.flatten()

matrix([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
         14., 15.]])

###### Ravel creates a view or copy of the array

In [57]:
A.ravel()

matrix([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
         14., 15.]])

###### Squeezing an array

In [63]:
X = np.array([[[1, 2], [3, 4]]])

In [64]:
X.squeeze()

array([[1, 2],
       [3, 4]])

###### Expanding Dimensions

In [84]:
Y = np.array([[1,2,3],[5, 6, 7]])

In [75]:
Y

array([[1, 2, 3],
       [5, 6, 7]])

In [78]:
np.expand_dims(Y, 1)

array([[[1, 2, 3]],

       [[5, 6, 7]]])

###### Transpose

In [79]:
Y.T

array([[1, 5],
       [2, 6],
       [3, 7]])

In [86]:
np.hstack(Y)

array([1, 2, 3, 5, 6, 7])

In [85]:
np.vstack(Y)

array([[1, 2, 3],
       [5, 6, 7]])

In [87]:
np.dstack(Y)

array([[[1, 5],
        [2, 6],
        [3, 7]]])

In [96]:
B = np.array([[1, 2, 3, 4, 5],[20, 30, 40, 50, 60],[11, 12, 13, 14, 15]])

In [100]:
np.concatenate([A, B], axis=1)

matrix([[ 1.,  2.,  3.,  4.,  5.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 20., 30., 40., 50., 60.],
        [11., 12., 13., 14., 15., 11., 12., 13., 14., 15.]])