In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2, 3],[4, 5, 6]])

In [3]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
B = np.array([[10, 20, 30],[40, 50, 60]])

In [5]:
A + B

array([[11, 22, 33],
       [44, 55, 66]])

In [6]:
A += A

In [7]:
A

array([[ 2,  4,  6],
       [ 8, 10, 12]])

##### Element-Wise Operation

In [8]:
np.sqrt(A)

array([[1.41421356, 2.        , 2.44948974],
       [2.82842712, 3.16227766, 3.46410162]])

In [9]:
np.exp(A)

array([[7.38905610e+00, 5.45981500e+01, 4.03428793e+02],
       [2.98095799e+03, 2.20264658e+04, 1.62754791e+05]])

##### Vectorized Function

In [18]:
def is_even(number):
    return number % 2

In [19]:
is_even(A)

array([[0, 0, 0],
       [0, 0, 0]])

In [20]:
np.vectorize(is_even)

In [21]:
is_even(A)

array([[0, 0, 0],
       [0, 0, 0]])

##### Aggregate Function

In [23]:
marks = np.array([[7, 8, 8],[7, 9, 9]])

In [24]:
np.mean(marks)

8.0

In [25]:
marks.sum()

48

In [26]:
marks.cumsum()

array([ 7, 15, 23, 30, 39, 48])

##### Aggregate Functions on Axis level

In [31]:
data = np.random.normal(size=(2, 3, 4))

In [32]:
data

array([[[ 0.17101882, -0.19790169,  1.37933813,  0.24478353],
        [-1.11301238,  1.55884429,  2.35312106, -0.70996891],
        [-0.15154099,  2.01965406, -0.31694224,  0.88878962]],

       [[ 1.63455116, -0.15513044,  0.37517676,  1.14596202],
        [-1.04479096, -1.08669579, -1.49152699,  0.28425264],
        [-0.21708892,  0.99850607,  0.54452683,  0.73322042]]])

In [40]:
data.sum(axis=(1,))

array([[-1.09353455,  3.38059665,  3.41551695,  0.42360424],
       [ 0.37267128, -0.24332016, -0.57182341,  2.16343509]])

##### Boolean Arrays

In [45]:
person1 = np.array([100, 56, 3])
person2 = np.array([175, 48, 10])

In [46]:
person1 > person2

array([False,  True, False])

In [48]:
1 * np.array(person1 > person2)

array([0, 1, 0])

##### Set Operations

In [51]:
heights = np.unique([100, 102, 100, 201, 102])

In [52]:
heights

array([100, 102, 201])

In [53]:
weights = np.array([50, 67, 98])

In [54]:
heights_and_weights = np.union1d(heights, weights)

In [55]:
heights_and_weights

array([ 50,  67,  98, 100, 102, 201])